src/http/device.ts
When push message is received, it might contain picture URL if user opted in to receive rich push notifications. In that scenarios, we can use this data to update latest picture URL so it will propagate to consumers as `property changed` event.
I was able to test and validate this change with Eufy Cam 2c only but updated all other devices when necessary.
=> propogate picture URL when motion/person detected

src/http/types.ts
Alarm mode was undefined when setting custom_1, custom_2, custom_3 guard mode.
Alarm mode can take `CUSTOM_1`, `CUSTOM_2` and `CUSTOM_3` value after some api tests.
logs in `eufy-security-ws`
```
2021-07-18 18:03:59.846  INFO Alarm mode for station T8010Nxxxxxxxx changed to: HOME 
2021-07-18 18:04:02.414  INFO Alarm mode for station T8010Nxxxxxxxx changed to: undefined 
2021-07-18 18:04:05.043  INFO Alarm mode for station T8010Nxxxxxxxx changed to: HOME 
2021-07-18 18:04:07.872  INFO Alarm mode for station T8010Nxxxxxxxx changed to: undefined 
```
This should fix the issue.
=> Add custom modes in alarm mode

src/http/station.ts, src/p2p/session.ts
Hey @bropat 
with a few fixes talkback works great for me:
- sequence number has to start with value 0, otherwise no audio data will be played by doorbell
- there was a logical bug where the library checked whether the station has the talkback command instead of checking for the device
- the whole talkback feature uses VIDEO-frames but the control messages are DATA-frames. Therefore the `p2pTalkback` and `p2pTalkbackChannel` settings are stored in the wrong messageState
=> fix: feature talkback

src/http/station.ts
As the Homebase 2 device (devic type 0) already listens for alarm events passed through the p2p connection, there is no need to listen to push data anymore.
This change excludes the Homebase 2 from emitting alarm events coming from push data.
=> Dont respond to alarm push events for Homebase 2

src/p2p/session.ts
I'm not really sure about this one.
I have never seen an alarm event from the push data with event numbers 0 and 1. They seem reserved for other purposes and not push data.
Now when I look at the events I effectively get an "alarm turned off" event when the alarm is armed, which is incorrect as there never was any alarm active.
This logic shouldn't bite the T8410 events mentioned in this PR: https://github.com/bropat/eufy-security-client/pull/151.
I have seen in the logging that it does not broadcast this alarm event when switching to an alarm enabled guard mode.
So judging by the data I see in the logging and what looks logical, I'd suggest _either_ emit an `alarm event` _or_ `alarm armed` event, not both.
=> Don't send the alarm armed p2p events as alarm events

src/http/station.ts
Starting a local livestream on Floodlight (T8420) fails due to wrong command used.
See [here](https://github.com/homebridge-eufy-security/plugin/issues/72) for reference.
This fixes this (tested), but could be the wrong approach.
I added the specific check for the serial since I don't know if all DeviceType.FLOODLIGHT are T8420 devices. If so a simple change from `!==` to `===` would suffice of course.
=> Fix: stream command for T8420

src/http/device.ts, src/http/types.ts, src/push/models.ts, src/push/service.ts, src/push/types.ts
After fiddling around with familiar faces, I noticed it actually works really well if you preload the faces.
The doorbell is somehow sh*t at detecting _new_ faces, but recognizes people with a good preloaded reference picture instantly.
Turns out the names of the people are also added in the push data (see below).
Considering this eufy data is an array, I changed the existing `personName` parameter to `peopleNames`.
I also added event type `3303` which is currently unhandled but is the `family spotted` event (eg. facial recognition got a match).
I **explicitly** did not create a separate "family detected" event as that's just eufy marketing BS. In the app you can label "family" as "Family", "Friend", "Neighbor", "Courier", "Others". Calling it "family recognition" sounds less privacy …
=> Dual Doorbell Family names

src/http/device.ts, src/http/station.ts
Sometimes a Homebase 1 is missing rawDevice.params and causing a crash
=> FIX: rawDevice params missing for Homebase 1

src/http/types.ts
The eufyCam 3c returns when fully charged the value 0 instead of 2 for the DeviceChargingStatusProperty. If this is also valid for the eufyCam 3 could not be verified (lack of hardware). Beside that, a left space at DeviceVideoStreamingQualityCamera3Property was removed (for value 6 Low).
=> Change DeviceChargingStatusProperty value for eufyCam 3c

src/http/api.ts
Update passport/profile to V2. V1 endpoint returns 403
=> FIX: support V2 for getPassportProfile (V1 deprecated)

src/p2p/session.ts
With the new implementation of the local p2p lockup, a P2P DID like `XXXXXXX-030810-YYYYY` will not be recognized as the wanted station, because the P2P DID in the LOCAL_LOOKUP_RESP message will be converted to `XXXXXXX-30810-YYYYY`. This is done by `msg.slice(12, 16).readUInt32BE()` because it returns a int value witch has no leading zeros. A possible workaround would be to add `.toString().padStart(6, '0')`, in the case that the number has always 6 digits.
If there could be another amount of digits in the P2P DID, we may must use a temporarily changed value for `this.rawStation.p2p_did`.
=> fix problem when the P2PDID number is starting with zeros

src/push/service.ts
The check for HB3 is preventing the integration to set the door Sensor Custom Push data 
In the logging of my Homey integration i see:
```
{
name: '',
event_time: -9205462985303130000,
type: 2,
station_sn: 'T8030REDACTED',
device_sn: 'T8900REDACTED',
title: 'Eufy Security',
content: 'Keukenraam is open',
push_time: 1681109148578,
channel: 0,
cipher: 0,
event_session: '',
event_type: 3,
file_path: '',
pic_url: '',
push_count: 1,
notification_style: undefined,
storage_type: 1,
msg_type: undefined,
person_name: undefined,
person_id: undefined,
tfcard_status: undefined,
user_type: undefined,
user_name: undefined,
station_guard_mode: undefined,
station_current_mode: undefined,
alarm_delay: undefined,
sound_alarm: undefined
}
```
=> FIX: HB3 connected sensors not reporting

src/http/types.ts
The `DeviceChargingStatus` property used by eufyCam 3c is also valid for the eufyCam 3.
=> Fix DeviceChargingStatus for eufyCam3

src/http/types.ts
The doorbells doesn't have a boolean status led property, they are using a numbered one.
=> Fixed StatusLed property for doorbell dual

src/http/types.ts
I was able to verify that the S100 wall light cam also supports storage info.
=> Storage info s100

src/eufysecurity.ts, src/interfaces.ts
For the Homey integration I would like to use config instead of a JSON file.
Some Homey devices do not have a disk were a file can be stored. But data can be persisted.
=> OPT: persistentData via config instead of JSON file

src/p2p/session.ts
A user of the ccu-addon (based on the eufy-security-client from current development branch) was receiving the following error message:
```
/usr/local/addons/eufySecurity/eufySecurityApi/p2p/session.js
else if (this.rawStation.devices !== undefined && this.rawStation.devices.length > 0 && device_1.Device.isLockWifiVideo(this.rawStation.devices[0].device_type)) {
^
TypeError: Cannot read properties of null (reading 'length')
at P2PClientProtocol.handleMsg (/usr/local/addons/eufySecurity/eufySecurityApi/p2p/session.js)
at Socket.<anonymous> (/usr/local/addons/eufySecurity/eufySecurityApi/p2p/session.js)
at Socket.emit (node:events:518:28)
at Socket.emit (node:domain:488:12)
at UDP.onMessage [as onmessage] (node:dgram:941:8)
```
After extending the line to
```
} else if …
```
=> Solve TypeError in handleMsg

src/http/device.ts
Looks like the Eufy API sometimes returns a numeric value for booleans. This PR adjust the boolean logic to update to use it.
It's also possible that open, delivery and masterpin uses more then a bool value and should be numeric.. Happy to adjust, just need to know how to grab that.
```
[http] [SmartDrop.convertRawPropertyValue] Device convert raw property - PropertyMetadataBoolean Convert Error {
error: {
cause: undefined,
message: 'TypeError: value.toLowerCase is not a function',
context: undefined,
stacktrace: 'TypeError: value.toLowerCase is not a function\n' +
'    at SmartDrop.convertRawPropertyValue (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:828:74)\n' +
'    at SmartDrop.convertRawPropertyValue (/usr/src/app/node_modules/eufy-security-client/build/http/dev …
```
=> fix(bool): convert numeric to boolean

src/http/types.ts
Once a camera gets added to the Homebase 3 it needs the DeviceTriggerAlarmSound
=> NEW: Add Device Alarm to multiple camers

src/http/types.ts
The battery percentage sensor for my Wall Cam 81A0 does not show up in the Eufy Security integration, even though the battery percentage for this camera is visible in the official Eufy app.
I compared this camera's configuration with the configuration of other cameras for which I do have access to their battery percentage, and everything was in the right place, except for one missing entry: the `DeviceBatteryProperty` in the `DeviceType.WALL_LIGHT_CAM_81A0` array in types.ts.
Add the missing entry
Unable to test, but I did try, without any success. I wish there were instructions to quickly and easily test changes from eufy-security-client in my own Home Assistant. @bropat - It would be of great help for potential contributors, and for the growth of this rep, to have a small guide for …
=> Add missing entry for Wall Cam 81A0 battery

src/p2p/session.ts
=> fix: Prevent crash in getLockSequenceNumber when devices is null

src/http/device.ts, src/http/station.ts, src/http/types.ts
Presets were recently added to the [`eufy-security`](https://github.com/fuatakgun/eufy_security) Home Assistant integration, but the T8423 is not supported yet (see [here](https://github.com/fuatakgun/eufy_security/pull/1332#issuecomment-2866581381) for more context).
Here is my attempt to implement it.
=> Add preset support for T8423

src/http/station.ts, src/p2p/session.ts
This refs to #668.
The lock T8806 has a station and a device. In contrast to the devices I know so far, the locks station has no devices in the devices array. So, I changed the `_getDeviceSerial` function to retrieve also the serial of the device of these stations to update the properties correctly.
=> Fix get device serial
